// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActivityFeed = `-- name: ListActivityFeed :many
SELECT a.id, a.type, a.actor_kind, a.created_at,
       u.email AS actor_email,
       k.name  AS key_name,
       l.tag   AS language_tag
FROM activity a
LEFT JOIN users u ON u.id = a.actor_id
LEFT JOIN translation_keys k ON k.id = a.key_id
LEFT JOIN languages l ON l.id = a.language_id
WHERE a.project_id = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type ListActivityFeedParams struct {
	ProjectID string `json:"projectId"`
	Limit     int32  `json:"limit"`
}

type ListActivityFeedRow struct {
	ID          string             `json:"id"`
	Type        ActivityType       `json:"type"`
	ActorKind   AuthorKind         `json:"actorKind"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	ActorEmail  pgtype.Text        `json:"actorEmail"`
	KeyName     pgtype.Text        `json:"keyName"`
	LanguageTag pgtype.Text        `json:"languageTag"`
}

// Recent project activity enriched for display. key_id/language_id are plain
// text (no FK), so LEFT JOINs tolerate deleted keys/languages.
func (q *Queries) ListActivityFeed(ctx context.Context, arg ListActivityFeedParams) ([]ListActivityFeedRow, error) {
	rows, err := q.db.Query(ctx, listActivityFeed, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityFeedRow{}
	for rows.Next() {
		var i ListActivityFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ActorKind,
			&i.CreatedAt,
			&i.ActorEmail,
			&i.KeyName,
			&i.LanguageTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
