// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, type, name, key_hash, prefix, scopes, owner_user_id, project_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, type, name, key_hash, prefix, scopes, owner_user_id, project_id, expires_at, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	ID          string             `json:"id"`
	Type        ApiKeyType         `json:"type"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"keyHash"`
	Prefix      string             `json:"prefix"`
	Scopes      []string           `json:"scopes"`
	OwnerUserID pgtype.Text        `json:"ownerUserId"`
	ProjectID   pgtype.Text        `json:"projectId"`
	ExpiresAt   pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
		arg.Scopes,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.Scopes,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.type, k.name, k.key_hash, k.prefix, k.scopes, k.owner_user_id, k.project_id, k.expires_at, k.last_used_at, k.revoked_at, k.created_at FROM api_keys k
LEFT JOIN users u ON u.id = k.owner_user_id
WHERE k.key_hash = $1
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > now())
  AND (k.owner_user_id IS NULL OR u.is_active = true)
`

// User-bound tokens (PATs, unlocked editor tokens) are rejected once their
// owner is deactivated — so deactivation immediately revokes access, mirroring
// session resolution. Unattended keys (no owner, e.g. read-only editor tokens)
// are unaffected.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.Scopes,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT id, type, name, key_hash, prefix, scopes, owner_user_id, project_id, expires_at, last_used_at, revoked_at, created_at FROM api_keys
WHERE project_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByProject(ctx context.Context, projectID pgtype.Text) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.Scopes,
			&i.OwnerUserID,
			&i.ProjectID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPATsByUser = `-- name: ListPATsByUser :many
SELECT id, type, name, key_hash, prefix, scopes, owner_user_id, project_id, expires_at, last_used_at, revoked_at, created_at FROM api_keys
WHERE owner_user_id = $1 AND type = 'pat' AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPATsByUser(ctx context.Context, ownerUserID pgtype.Text) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listPATsByUser, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.Scopes,
			&i.OwnerUserID,
			&i.ProjectID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
