// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, translation_id, key_id, author_id, body, parent_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, translation_id, key_id, author_id, body, parent_id, resolved_at, resolved_by, created_at, updated_at
`

type CreateCommentParams struct {
	ID            string      `json:"id"`
	TranslationID pgtype.Text `json:"translationId"`
	KeyID         pgtype.Text `json:"keyId"`
	AuthorID      string      `json:"authorId"`
	Body          string      `json:"body"`
	ParentID      pgtype.Text `json:"parentId"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.TranslationID,
		arg.KeyID,
		arg.AuthorID,
		arg.Body,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TranslationID,
		&i.KeyID,
		&i.AuthorID,
		&i.Body,
		&i.ParentID,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, translation_id, key_id, author_id, body, parent_id, resolved_at, resolved_by, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TranslationID,
		&i.KeyID,
		&i.AuthorID,
		&i.Body,
		&i.ParentID,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentProjectID = `-- name: GetCommentProjectID :one
SELECT k.project_id
FROM comments c
LEFT JOIN translations t ON t.id = c.translation_id
JOIN translation_keys k ON k.id = COALESCE(c.key_id, t.key_id)
WHERE c.id = $1
`

func (q *Queries) GetCommentProjectID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getCommentProjectID, id)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}

const listCommentsForTranslation = `-- name: ListCommentsForTranslation :many
SELECT c.id, c.translation_id, c.key_id, c.author_id, c.body, c.parent_id,
       c.resolved_at, c.resolved_by, c.created_at, c.updated_at,
       u.email AS author_email, u.name AS author_name
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.translation_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsForTranslationRow struct {
	ID            string             `json:"id"`
	TranslationID pgtype.Text        `json:"translationId"`
	KeyID         pgtype.Text        `json:"keyId"`
	AuthorID      string             `json:"authorId"`
	Body          string             `json:"body"`
	ParentID      pgtype.Text        `json:"parentId"`
	ResolvedAt    pgtype.Timestamptz `json:"resolvedAt"`
	ResolvedBy    pgtype.Text        `json:"resolvedBy"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	AuthorEmail   string             `json:"authorEmail"`
	AuthorName    pgtype.Text        `json:"authorName"`
}

func (q *Queries) ListCommentsForTranslation(ctx context.Context, translationID pgtype.Text) ([]ListCommentsForTranslationRow, error) {
	rows, err := q.db.Query(ctx, listCommentsForTranslation, translationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsForTranslationRow{}
	for rows.Next() {
		var i ListCommentsForTranslationRow
		if err := rows.Scan(
			&i.ID,
			&i.TranslationID,
			&i.KeyID,
			&i.AuthorID,
			&i.Body,
			&i.ParentID,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorEmail,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveComment = `-- name: ResolveComment :one
UPDATE comments SET resolved_at = now(), resolved_by = $2, updated_at = now()
WHERE id = $1
RETURNING id, translation_id, key_id, author_id, body, parent_id, resolved_at, resolved_by, created_at, updated_at
`

type ResolveCommentParams struct {
	ID         string      `json:"id"`
	ResolvedBy pgtype.Text `json:"resolvedBy"`
}

func (q *Queries) ResolveComment(ctx context.Context, arg ResolveCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, resolveComment, arg.ID, arg.ResolvedBy)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TranslationID,
		&i.KeyID,
		&i.AuthorID,
		&i.Body,
		&i.ParentID,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unresolveComment = `-- name: UnresolveComment :one
UPDATE comments SET resolved_at = NULL, resolved_by = NULL, updated_at = now()
WHERE id = $1
RETURNING id, translation_id, key_id, author_id, body, parent_id, resolved_at, resolved_by, created_at, updated_at
`

func (q *Queries) UnresolveComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRow(ctx, unresolveComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TranslationID,
		&i.KeyID,
		&i.AuthorID,
		&i.Body,
		&i.ParentID,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
