// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: glossary.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGlossaryTerm = `-- name: CreateGlossaryTerm :one
INSERT INTO glossary_terms (id, project_id, term, description, case_sensitive, do_not_translate)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, term, description, case_sensitive, do_not_translate, created_at
`

type CreateGlossaryTermParams struct {
	ID             string `json:"id"`
	ProjectID      string `json:"projectId"`
	Term           string `json:"term"`
	Description    string `json:"description"`
	CaseSensitive  bool   `json:"caseSensitive"`
	DoNotTranslate bool   `json:"doNotTranslate"`
}

func (q *Queries) CreateGlossaryTerm(ctx context.Context, arg CreateGlossaryTermParams) (GlossaryTerm, error) {
	row := q.db.QueryRow(ctx, createGlossaryTerm,
		arg.ID,
		arg.ProjectID,
		arg.Term,
		arg.Description,
		arg.CaseSensitive,
		arg.DoNotTranslate,
	)
	var i GlossaryTerm
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Term,
		&i.Description,
		&i.CaseSensitive,
		&i.DoNotTranslate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGlossaryTerm = `-- name: DeleteGlossaryTerm :exec
DELETE FROM glossary_terms WHERE id = $1
`

func (q *Queries) DeleteGlossaryTerm(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGlossaryTerm, id)
	return err
}

const getGlossaryTerm = `-- name: GetGlossaryTerm :one
SELECT id, project_id, term, description, case_sensitive, do_not_translate, created_at FROM glossary_terms WHERE id = $1
`

func (q *Queries) GetGlossaryTerm(ctx context.Context, id string) (GlossaryTerm, error) {
	row := q.db.QueryRow(ctx, getGlossaryTerm, id)
	var i GlossaryTerm
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Term,
		&i.Description,
		&i.CaseSensitive,
		&i.DoNotTranslate,
		&i.CreatedAt,
	)
	return i, err
}

const listGlossaryTerms = `-- name: ListGlossaryTerms :many
SELECT id, project_id, term, description, case_sensitive, do_not_translate, created_at FROM glossary_terms WHERE project_id = $1 ORDER BY term
`

func (q *Queries) ListGlossaryTerms(ctx context.Context, projectID string) ([]GlossaryTerm, error) {
	rows, err := q.db.Query(ctx, listGlossaryTerms, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlossaryTerm{}
	for rows.Next() {
		var i GlossaryTerm
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Term,
			&i.Description,
			&i.CaseSensitive,
			&i.DoNotTranslate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlossaryTranslationsByProject = `-- name: ListGlossaryTranslationsByProject :many
SELECT gt.id, gt.term_id, gt.language_id, gt.text FROM glossary_translations gt
JOIN glossary_terms t ON t.id = gt.term_id
WHERE t.project_id = $1
`

func (q *Queries) ListGlossaryTranslationsByProject(ctx context.Context, projectID string) ([]GlossaryTranslation, error) {
	rows, err := q.db.Query(ctx, listGlossaryTranslationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlossaryTranslation{}
	for rows.Next() {
		var i GlossaryTranslation
		if err := rows.Scan(
			&i.ID,
			&i.TermID,
			&i.LanguageID,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchGlossary = `-- name: MatchGlossary :many
SELECT t.term, t.do_not_translate, gt.text AS translation
FROM glossary_terms t
LEFT JOIN glossary_translations gt
  ON gt.term_id = t.id AND gt.language_id = $1
WHERE t.project_id = $2
  AND CASE WHEN t.case_sensitive
           THEN $3 LIKE '%' || t.term || '%'
           ELSE $3 ILIKE '%' || t.term || '%' END
`

type MatchGlossaryParams struct {
	TargetLanguageID string `json:"targetLanguageId"`
	ProjectID        string `json:"projectId"`
	SourceText       string `json:"sourceText"`
}

type MatchGlossaryRow struct {
	Term           string      `json:"term"`
	DoNotTranslate bool        `json:"doNotTranslate"`
	Translation    pgtype.Text `json:"translation"`
}

func (q *Queries) MatchGlossary(ctx context.Context, arg MatchGlossaryParams) ([]MatchGlossaryRow, error) {
	rows, err := q.db.Query(ctx, matchGlossary, arg.TargetLanguageID, arg.ProjectID, arg.SourceText)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchGlossaryRow{}
	for rows.Next() {
		var i MatchGlossaryRow
		if err := rows.Scan(&i.Term, &i.DoNotTranslate, &i.Translation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGlossaryTranslation = `-- name: UpsertGlossaryTranslation :one
INSERT INTO glossary_translations (id, term_id, language_id, text)
VALUES ($1, $2, $3, $4)
ON CONFLICT (term_id, language_id) DO UPDATE SET text = EXCLUDED.text
RETURNING id, term_id, language_id, text
`

type UpsertGlossaryTranslationParams struct {
	ID         string `json:"id"`
	TermID     string `json:"termId"`
	LanguageID string `json:"languageId"`
	Text       string `json:"text"`
}

func (q *Queries) UpsertGlossaryTranslation(ctx context.Context, arg UpsertGlossaryTranslationParams) (GlossaryTranslation, error) {
	row := q.db.QueryRow(ctx, upsertGlossaryTranslation,
		arg.ID,
		arg.TermID,
		arg.LanguageID,
		arg.Text,
	)
	var i GlossaryTranslation
	err := row.Scan(
		&i.ID,
		&i.TermID,
		&i.LanguageID,
		&i.Text,
	)
	return i, err
}
