// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countKeys = `-- name: CountKeys :one
SELECT count(*) FROM translation_keys WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountKeys(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countKeys, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKey = `-- name: CreateKey :one
INSERT INTO translation_keys (id, project_id, namespace_id, name, description, is_plural)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, namespace_id, name, description, is_plural, source_hash, tags, created_at, updated_at, deleted_at
`

type CreateKeyParams struct {
	ID          string      `json:"id"`
	ProjectID   string      `json:"projectId"`
	NamespaceID pgtype.Text `json:"namespaceId"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsPlural    bool        `json:"isPlural"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (TranslationKey, error) {
	row := q.db.QueryRow(ctx, createKey,
		arg.ID,
		arg.ProjectID,
		arg.NamespaceID,
		arg.Name,
		arg.Description,
		arg.IsPlural,
	)
	var i TranslationKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.IsPlural,
		&i.SourceHash,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getKey = `-- name: GetKey :one
SELECT id, project_id, namespace_id, name, description, is_plural, source_hash, tags, created_at, updated_at, deleted_at FROM translation_keys WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetKey(ctx context.Context, id string) (TranslationKey, error) {
	row := q.db.QueryRow(ctx, getKey, id)
	var i TranslationKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.IsPlural,
		&i.SourceHash,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listKeys = `-- name: ListKeys :many
SELECT id, project_id, namespace_id, name, description, is_plural, source_hash, tags, created_at, updated_at, deleted_at FROM translation_keys
WHERE project_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR namespace_id = $2)
  AND ($3::text IS NULL OR name ILIKE '%' || $3 || '%')
ORDER BY name
LIMIT $5 OFFSET $4
`

type ListKeysParams struct {
	ProjectID   string      `json:"projectId"`
	NamespaceID pgtype.Text `json:"namespaceId"`
	Search      pgtype.Text `json:"search"`
	Off         int32       `json:"off"`
	Lim         int32       `json:"lim"`
}

func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]TranslationKey, error) {
	rows, err := q.db.Query(ctx, listKeys,
		arg.ProjectID,
		arg.NamespaceID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranslationKey{}
	for rows.Next() {
		var i TranslationKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.NamespaceID,
			&i.Name,
			&i.Description,
			&i.IsPlural,
			&i.SourceHash,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKeySourceHash = `-- name: SetKeySourceHash :exec
UPDATE translation_keys SET source_hash = $2, updated_at = now() WHERE id = $1
`

type SetKeySourceHashParams struct {
	ID         string      `json:"id"`
	SourceHash pgtype.Text `json:"sourceHash"`
}

func (q *Queries) SetKeySourceHash(ctx context.Context, arg SetKeySourceHashParams) error {
	_, err := q.db.Exec(ctx, setKeySourceHash, arg.ID, arg.SourceHash)
	return err
}

const softDeleteKey = `-- name: SoftDeleteKey :exec
UPDATE translation_keys SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteKey, id)
	return err
}

const updateKey = `-- name: UpdateKey :one
UPDATE translation_keys
SET description = $2, is_plural = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, namespace_id, name, description, is_plural, source_hash, tags, created_at, updated_at, deleted_at
`

type UpdateKeyParams struct {
	ID          string      `json:"id"`
	Description pgtype.Text `json:"description"`
	IsPlural    bool        `json:"isPlural"`
}

func (q *Queries) UpdateKey(ctx context.Context, arg UpdateKeyParams) (TranslationKey, error) {
	row := q.db.QueryRow(ctx, updateKey, arg.ID, arg.Description, arg.IsPlural)
	var i TranslationKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.IsPlural,
		&i.SourceHash,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
