// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: languages.sql

package db

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (id, project_id, tag, name, is_rtl, plural_forms)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, tag, name, is_rtl, plural_forms, created_at
`

type CreateLanguageParams struct {
	ID          string   `json:"id"`
	ProjectID   string   `json:"projectId"`
	Tag         string   `json:"tag"`
	Name        string   `json:"name"`
	IsRtl       bool     `json:"isRtl"`
	PluralForms []string `json:"pluralForms"`
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage,
		arg.ID,
		arg.ProjectID,
		arg.Tag,
		arg.Name,
		arg.IsRtl,
		arg.PluralForms,
	)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Tag,
		&i.Name,
		&i.IsRtl,
		&i.PluralForms,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLanguage = `-- name: DeleteLanguage :exec
DELETE FROM languages WHERE id = $1
`

func (q *Queries) DeleteLanguage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLanguage, id)
	return err
}

const getLanguage = `-- name: GetLanguage :one
SELECT id, project_id, tag, name, is_rtl, plural_forms, created_at FROM languages WHERE id = $1
`

func (q *Queries) GetLanguage(ctx context.Context, id string) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguage, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Tag,
		&i.Name,
		&i.IsRtl,
		&i.PluralForms,
		&i.CreatedAt,
	)
	return i, err
}

const getLanguageByTag = `-- name: GetLanguageByTag :one
SELECT id, project_id, tag, name, is_rtl, plural_forms, created_at FROM languages WHERE project_id = $1 AND tag = $2
`

type GetLanguageByTagParams struct {
	ProjectID string `json:"projectId"`
	Tag       string `json:"tag"`
}

func (q *Queries) GetLanguageByTag(ctx context.Context, arg GetLanguageByTagParams) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguageByTag, arg.ProjectID, arg.Tag)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Tag,
		&i.Name,
		&i.IsRtl,
		&i.PluralForms,
		&i.CreatedAt,
	)
	return i, err
}

const listLanguages = `-- name: ListLanguages :many
SELECT id, project_id, tag, name, is_rtl, plural_forms, created_at FROM languages WHERE project_id = $1 ORDER BY tag
`

func (q *Queries) ListLanguages(ctx context.Context, projectID string) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Tag,
			&i.Name,
			&i.IsRtl,
			&i.PluralForms,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
