// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityType string

const (
	ActivityTypeKeyCreated              ActivityType = "key_created"
	ActivityTypeKeyUpdated              ActivityType = "key_updated"
	ActivityTypeKeyDeleted              ActivityType = "key_deleted"
	ActivityTypeTranslationUpdated      ActivityType = "translation_updated"
	ActivityTypeTranslationStateChanged ActivityType = "translation_state_changed"
	ActivityTypeSourceChanged           ActivityType = "source_changed"
	ActivityTypeCommentAdded            ActivityType = "comment_added"
	ActivityTypeCommentResolved         ActivityType = "comment_resolved"
	ActivityTypeImportCompleted         ActivityType = "import_completed"
	ActivityTypeExportRun               ActivityType = "export_run"
	ActivityTypeMemberAdded             ActivityType = "member_added"
	ActivityTypeMemberRemoved           ActivityType = "member_removed"
	ActivityTypeScreenshotAdded         ActivityType = "screenshot_added"
	ActivityTypeAutoTranslateRun        ActivityType = "auto_translate_run"
)

func (e *ActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityType(s)
	case string:
		*e = ActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityType: %T", src)
	}
	return nil
}

type NullActivityType struct {
	ActivityType ActivityType `json:"activityType"`
	Valid        bool         `json:"valid"` // Valid is true if ActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityType), nil
}

type ApiKeyType string

const (
	ApiKeyTypePat     ApiKeyType = "pat"
	ApiKeyTypeProject ApiKeyType = "project"
	ApiKeyTypeEditor  ApiKeyType = "editor"
)

func (e *ApiKeyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiKeyType(s)
	case string:
		*e = ApiKeyType(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiKeyType: %T", src)
	}
	return nil
}

type NullApiKeyType struct {
	ApiKeyType ApiKeyType `json:"apiKeyType"`
	Valid      bool       `json:"valid"` // Valid is true if ApiKeyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiKeyType) Scan(value interface{}) error {
	if value == nil {
		ns.ApiKeyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiKeyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiKeyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiKeyType), nil
}

type AuthorKind string

const (
	AuthorKindUser   AuthorKind = "user"
	AuthorKindApiKey AuthorKind = "api_key"
	AuthorKindSystem AuthorKind = "system"
	AuthorKindMt     AuthorKind = "mt"
)

func (e *AuthorKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthorKind(s)
	case string:
		*e = AuthorKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthorKind: %T", src)
	}
	return nil
}

type NullAuthorKind struct {
	AuthorKind AuthorKind `json:"authorKind"`
	Valid      bool       `json:"valid"` // Valid is true if AuthorKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthorKind) Scan(value interface{}) error {
	if value == nil {
		ns.AuthorKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthorKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthorKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthorKind), nil
}

type OrgRole string

const (
	OrgRoleOwner  OrgRole = "owner"
	OrgRoleAdmin  OrgRole = "admin"
	OrgRoleMember OrgRole = "member"
)

func (e *OrgRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgRole(s)
	case string:
		*e = OrgRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgRole: %T", src)
	}
	return nil
}

type NullOrgRole struct {
	OrgRole OrgRole `json:"orgRole"`
	Valid   bool    `json:"valid"` // Valid is true if OrgRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrgRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgRole), nil
}

type ProjectRole string

const (
	ProjectRoleOwner      ProjectRole = "owner"
	ProjectRoleAdmin      ProjectRole = "admin"
	ProjectRoleDeveloper  ProjectRole = "developer"
	ProjectRoleTranslator ProjectRole = "translator"
	ProjectRoleReviewer   ProjectRole = "reviewer"
)

func (e *ProjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectRole(s)
	case string:
		*e = ProjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectRole: %T", src)
	}
	return nil
}

type NullProjectRole struct {
	ProjectRole ProjectRole `json:"projectRole"`
	Valid       bool        `json:"valid"` // Valid is true if ProjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectRole), nil
}

type TaskStatus string

const (
	TaskStatusQueued    TaskStatus = "queued"
	TaskStatusRunning   TaskStatus = "running"
	TaskStatusSucceeded TaskStatus = "succeeded"
	TaskStatusFailed    TaskStatus = "failed"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"taskStatus"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TaskType string

const (
	TaskTypeImport          TaskType = "import"
	TaskTypeExport          TaskType = "export"
	TaskTypeBulkTranslation TaskType = "bulk_translation"
	TaskTypeAutoTranslate   TaskType = "auto_translate"
	TaskTypeTmReindex       TaskType = "tm_reindex"
	TaskTypeScreenshotOcr   TaskType = "screenshot_ocr"
	TaskTypeWebhookDelivery TaskType = "webhook_delivery"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType `json:"taskType"`
	Valid    bool     `json:"valid"` // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type TranslationOrigin string

const (
	TranslationOriginHuman     TranslationOrigin = "human"
	TranslationOriginMachineMt TranslationOrigin = "machine_mt"
	TranslationOriginMachineTm TranslationOrigin = "machine_tm"
	TranslationOriginImport    TranslationOrigin = "import"
	TranslationOriginAuto      TranslationOrigin = "auto"
)

func (e *TranslationOrigin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranslationOrigin(s)
	case string:
		*e = TranslationOrigin(s)
	default:
		return fmt.Errorf("unsupported scan type for TranslationOrigin: %T", src)
	}
	return nil
}

type NullTranslationOrigin struct {
	TranslationOrigin TranslationOrigin `json:"translationOrigin"`
	Valid             bool              `json:"valid"` // Valid is true if TranslationOrigin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranslationOrigin) Scan(value interface{}) error {
	if value == nil {
		ns.TranslationOrigin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranslationOrigin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranslationOrigin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranslationOrigin), nil
}

type TranslationState string

const (
	TranslationStateUntranslated TranslationState = "untranslated"
	TranslationStateTranslated   TranslationState = "translated"
	TranslationStateReviewed     TranslationState = "reviewed"
	TranslationStateNeedsWork    TranslationState = "needs_work"
	TranslationStateOutdated     TranslationState = "outdated"
)

func (e *TranslationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranslationState(s)
	case string:
		*e = TranslationState(s)
	default:
		return fmt.Errorf("unsupported scan type for TranslationState: %T", src)
	}
	return nil
}

type NullTranslationState struct {
	TranslationState TranslationState `json:"translationState"`
	Valid            bool             `json:"valid"` // Valid is true if TranslationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranslationState) Scan(value interface{}) error {
	if value == nil {
		ns.TranslationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranslationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranslationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranslationState), nil
}

type Activity struct {
	ID            string             `json:"id"`
	ProjectID     string             `json:"projectId"`
	Type          ActivityType       `json:"type"`
	ActorID       pgtype.Text        `json:"actorId"`
	ActorKind     AuthorKind         `json:"actorKind"`
	KeyID         pgtype.Text        `json:"keyId"`
	TranslationID pgtype.Text        `json:"translationId"`
	LanguageID    pgtype.Text        `json:"languageId"`
	Meta          []byte             `json:"meta"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type ApiKey struct {
	ID          string             `json:"id"`
	Type        ApiKeyType         `json:"type"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"keyHash"`
	Prefix      string             `json:"prefix"`
	Scopes      []string           `json:"scopes"`
	OwnerUserID pgtype.Text        `json:"ownerUserId"`
	ProjectID   pgtype.Text        `json:"projectId"`
	ExpiresAt   pgtype.Timestamptz `json:"expiresAt"`
	LastUsedAt  pgtype.Timestamptz `json:"lastUsedAt"`
	RevokedAt   pgtype.Timestamptz `json:"revokedAt"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type Comment struct {
	ID            string             `json:"id"`
	TranslationID pgtype.Text        `json:"translationId"`
	KeyID         pgtype.Text        `json:"keyId"`
	AuthorID      string             `json:"authorId"`
	Body          string             `json:"body"`
	ParentID      pgtype.Text        `json:"parentId"`
	ResolvedAt    pgtype.Timestamptz `json:"resolvedAt"`
	ResolvedBy    pgtype.Text        `json:"resolvedBy"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type GlossaryTerm struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"projectId"`
	Term           string             `json:"term"`
	Description    string             `json:"description"`
	CaseSensitive  bool               `json:"caseSensitive"`
	DoNotTranslate bool               `json:"doNotTranslate"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}

type GlossaryTranslation struct {
	ID         string `json:"id"`
	TermID     string `json:"termId"`
	LanguageID string `json:"languageId"`
	Text       string `json:"text"`
}

type Language struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"projectId"`
	Tag         string             `json:"tag"`
	Name        string             `json:"name"`
	IsRtl       bool               `json:"isRtl"`
	PluralForms []string           `json:"pluralForms"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type MtConfig struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"projectId"`
	Provider    string             `json:"provider"`
	Enabled     bool               `json:"enabled"`
	Model       string             `json:"model"`
	Credentials []byte             `json:"credentials"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Namespace struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"projectId"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type OrgMembership struct {
	ID        string             `json:"id"`
	OrgID     string             `json:"orgId"`
	UserID    string             `json:"userId"`
	Role      OrgRole            `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type Organization struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Project struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"orgId"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	BaseLanguageID pgtype.Text        `json:"baseLanguageId"`
	IcuEnabled     bool               `json:"icuEnabled"`
	AutoTranslate  bool               `json:"autoTranslate"`
	MtProvider     pgtype.Text        `json:"mtProvider"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt      pgtype.Timestamptz `json:"deletedAt"`
}

type ProjectMember struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"projectId"`
	UserID    string             `json:"userId"`
	Role      ProjectRole        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type ProjectMemberLanguage struct {
	MemberID   string `json:"memberId"`
	LanguageID string `json:"languageId"`
}

type Screenshot struct {
	ID         string             `json:"id"`
	ProjectID  string             `json:"projectId"`
	StorageKey string             `json:"storageKey"`
	Name       string             `json:"name"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	CreatedBy  pgtype.Text        `json:"createdBy"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type ScreenshotRegion struct {
	ID            string             `json:"id"`
	ScreenshotID  string             `json:"screenshotId"`
	KeyID         string             `json:"keyId"`
	TranslationID pgtype.Text        `json:"translationId"`
	X             int32              `json:"x"`
	Y             int32              `json:"y"`
	W             int32              `json:"w"`
	H             int32              `json:"h"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    string             `json:"userId"`
	TokenHash string             `json:"tokenHash"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	UserAgent pgtype.Text        `json:"userAgent"`
	Ip        pgtype.Text        `json:"ip"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type Task struct {
	ID         string             `json:"id"`
	ProjectID  pgtype.Text        `json:"projectId"`
	Type       TaskType           `json:"type"`
	Status     TaskStatus         `json:"status"`
	Progress   int32              `json:"progress"`
	Total      pgtype.Int4        `json:"total"`
	Processed  pgtype.Int4        `json:"processed"`
	Result     []byte             `json:"result"`
	Error      pgtype.Text        `json:"error"`
	CreatedBy  pgtype.Text        `json:"createdBy"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	StartedAt  pgtype.Timestamptz `json:"startedAt"`
	FinishedAt pgtype.Timestamptz `json:"finishedAt"`
}

type TmSegment struct {
	ID         string             `json:"id"`
	ProjectID  string             `json:"projectId"`
	SourceLang string             `json:"sourceLang"`
	TargetLang string             `json:"targetLang"`
	SourceText string             `json:"sourceText"`
	TargetText string             `json:"targetText"`
	SourceHash string             `json:"sourceHash"`
	KeyID      pgtype.Text        `json:"keyId"`
	Origin     string             `json:"origin"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type Translation struct {
	ID         string             `json:"id"`
	KeyID      string             `json:"keyId"`
	LanguageID string             `json:"languageId"`
	Text       pgtype.Text        `json:"text"`
	State      TranslationState   `json:"state"`
	Origin     TranslationOrigin  `json:"origin"`
	IsMachine  bool               `json:"isMachine"`
	SubID      pgtype.Int8        `json:"subId"`
	Version    int32              `json:"version"`
	UpdatedBy  pgtype.Text        `json:"updatedBy"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type TranslationHistory struct {
	ID            string               `json:"id"`
	TranslationID string               `json:"translationId"`
	KeyID         string               `json:"keyId"`
	LanguageID    string               `json:"languageId"`
	OldText       pgtype.Text          `json:"oldText"`
	NewText       pgtype.Text          `json:"newText"`
	OldState      NullTranslationState `json:"oldState"`
	NewState      NullTranslationState `json:"newState"`
	Origin        TranslationOrigin    `json:"origin"`
	AuthorKind    AuthorKind           `json:"authorKind"`
	AuthorID      pgtype.Text          `json:"authorId"`
	ApiKeyID      pgtype.Text          `json:"apiKeyId"`
	CreatedAt     pgtype.Timestamptz   `json:"createdAt"`
}

type TranslationKey struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"projectId"`
	NamespaceID pgtype.Text        `json:"namespaceId"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsPlural    bool               `json:"isPlural"`
	SourceHash  pgtype.Text        `json:"sourceHash"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"passwordHash"`
	Name         pgtype.Text        `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatarUrl"`
	IsActive     bool               `json:"isActive"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Webhook struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"projectId"`
	Url       string             `json:"url"`
	Secret    []byte             `json:"secret"`
	Events    []string           `json:"events"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type WebhookDelivery struct {
	ID         string             `json:"id"`
	WebhookID  string             `json:"webhookId"`
	Event      string             `json:"event"`
	StatusCode int32              `json:"statusCode"`
	Success    bool               `json:"success"`
	Error      string             `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}
