// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mt_config.sql

package db

import (
	"context"
)

const deleteMTConfig = `-- name: DeleteMTConfig :exec
DELETE FROM mt_config WHERE project_id = $1
`

func (q *Queries) DeleteMTConfig(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteMTConfig, projectID)
	return err
}

const getMTConfig = `-- name: GetMTConfig :one
SELECT id, project_id, provider, enabled, model, credentials, created_at, updated_at FROM mt_config WHERE project_id = $1
`

func (q *Queries) GetMTConfig(ctx context.Context, projectID string) (MtConfig, error) {
	row := q.db.QueryRow(ctx, getMTConfig, projectID)
	var i MtConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Enabled,
		&i.Model,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMTConfig = `-- name: UpsertMTConfig :one
INSERT INTO mt_config (id, project_id, provider, enabled, model, credentials)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (project_id) DO UPDATE SET
  provider = EXCLUDED.provider,
  enabled = EXCLUDED.enabled,
  model = EXCLUDED.model,
  credentials = EXCLUDED.credentials,
  updated_at = now()
RETURNING id, project_id, provider, enabled, model, credentials, created_at, updated_at
`

type UpsertMTConfigParams struct {
	ID          string `json:"id"`
	ProjectID   string `json:"projectId"`
	Provider    string `json:"provider"`
	Enabled     bool   `json:"enabled"`
	Model       string `json:"model"`
	Credentials []byte `json:"credentials"`
}

func (q *Queries) UpsertMTConfig(ctx context.Context, arg UpsertMTConfigParams) (MtConfig, error) {
	row := q.db.QueryRow(ctx, upsertMTConfig,
		arg.ID,
		arg.ProjectID,
		arg.Provider,
		arg.Enabled,
		arg.Model,
		arg.Credentials,
	)
	var i MtConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Enabled,
		&i.Model,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
