// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: namespaces.sql

package db

import (
	"context"
)

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (id, project_id, name) VALUES ($1, $2, $3) RETURNING id, project_id, name, created_at
`

type CreateNamespaceParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"projectId"`
	Name      string `json:"name"`
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, createNamespace, arg.ID, arg.ProjectID, arg.Name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, project_id, name, created_at FROM namespaces WHERE project_id = $1 AND name = $2
`

type GetNamespaceByNameParams struct {
	ProjectID string `json:"projectId"`
	Name      string `json:"name"`
}

func (q *Queries) GetNamespaceByName(ctx context.Context, arg GetNamespaceByNameParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, getNamespaceByName, arg.ProjectID, arg.Name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, project_id, name, created_at FROM namespaces WHERE project_id = $1 ORDER BY name
`

func (q *Queries) ListNamespaces(ctx context.Context, projectID string) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, listNamespaces, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
