// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orgs.sql

package db

import (
	"context"
)

const createOrgMembership = `-- name: CreateOrgMembership :one
INSERT INTO org_memberships (id, org_id, user_id, role) VALUES ($1, $2, $3, $4) RETURNING id, org_id, user_id, role, created_at
`

type CreateOrgMembershipParams struct {
	ID     string  `json:"id"`
	OrgID  string  `json:"orgId"`
	UserID string  `json:"userId"`
	Role   OrgRole `json:"role"`
}

func (q *Queries) CreateOrgMembership(ctx context.Context, arg CreateOrgMembershipParams) (OrgMembership, error) {
	row := q.db.QueryRow(ctx, createOrgMembership,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Role,
	)
	var i OrgMembership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug) VALUES ($1, $2, $3) RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at FROM organizations o
JOIN org_memberships m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at
`

func (q *Queries) ListUserOrganizations(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
