// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, org_id, name, slug, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, slug, description, base_language_id, icu_enabled, auto_translate, mt_provider, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	ID          string      `json:"id"`
	OrgID       string      `json:"orgId"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BaseLanguageID,
		&i.IcuEnabled,
		&i.AutoTranslate,
		&i.MtProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProjectMember = `-- name: CreateProjectMember :one
INSERT INTO project_members (id, project_id, user_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, user_id, role, created_at
`

type CreateProjectMemberParams struct {
	ID        string      `json:"id"`
	ProjectID string      `json:"projectId"`
	UserID    string      `json:"userId"`
	Role      ProjectRole `json:"role"`
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, createProjectMember,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, name, slug, description, base_language_id, icu_enabled, auto_translate, mt_provider, created_at, updated_at, deleted_at FROM projects WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BaseLanguageID,
		&i.IcuEnabled,
		&i.AutoTranslate,
		&i.MtProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.id, pm.project_id, pm.user_id, pm.role, pm.created_at, u.email, u.name
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY pm.created_at
`

type ListProjectMembersRow struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"projectId"`
	UserID    string             `json:"userId"`
	Role      ProjectRole        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT DISTINCT p.id, p.org_id, p.name, p.slug, p.description, p.base_language_id,
       p.icu_enabled, p.auto_translate, p.mt_provider, p.created_at, p.updated_at, p.deleted_at
FROM projects p
LEFT JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = $1
LEFT JOIN org_memberships om ON om.org_id = p.org_id AND om.user_id = $1
WHERE p.deleted_at IS NULL
  AND (pm.user_id IS NOT NULL OR om.role IN ('owner', 'admin'))
ORDER BY p.created_at DESC
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.BaseLanguageID,
			&i.IcuEnabled,
			&i.AutoTranslate,
			&i.MtProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectBaseLanguage = `-- name: SetProjectBaseLanguage :exec
UPDATE projects SET base_language_id = $2, updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

type SetProjectBaseLanguageParams struct {
	ID             string      `json:"id"`
	BaseLanguageID pgtype.Text `json:"baseLanguageId"`
}

func (q *Queries) SetProjectBaseLanguage(ctx context.Context, arg SetProjectBaseLanguageParams) error {
	_, err := q.db.Exec(ctx, setProjectBaseLanguage, arg.ID, arg.BaseLanguageID)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, name, slug, description, base_language_id, icu_enabled, auto_translate, mt_provider, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BaseLanguageID,
		&i.IcuEnabled,
		&i.AutoTranslate,
		&i.MtProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
