// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountKeys(ctx context.Context, projectID string) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateKey(ctx context.Context, arg CreateKeyParams) (TranslationKey, error)
	CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error)
	CreateNamespace(ctx context.Context, arg CreateNamespaceParams) (Namespace, error)
	CreateOrgMembership(ctx context.Context, arg CreateOrgMembershipParams) (OrgMembership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error)
	CreateScreenshot(ctx context.Context, arg CreateScreenshotParams) (Screenshot, error)
	CreateScreenshotRegion(ctx context.Context, arg CreateScreenshotRegionParams) (ScreenshotRegion, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTranslation(ctx context.Context, arg CreateTranslationParams) (Translation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteLanguage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetComment(ctx context.Context, id string) (Comment, error)
	GetCommentProjectID(ctx context.Context, id string) (string, error)
	GetKey(ctx context.Context, id string) (TranslationKey, error)
	GetLanguage(ctx context.Context, id string) (Language, error)
	GetLanguageByTag(ctx context.Context, arg GetLanguageByTagParams) (Language, error)
	GetNamespaceByName(ctx context.Context, arg GetNamespaceByNameParams) (Namespace, error)
	GetOrgMembership(ctx context.Context, arg GetOrgMembershipParams) (OrgMembership, error)
	GetOrganization(ctx context.Context, id string) (Organization, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectForAuth(ctx context.Context, id string) (GetProjectForAuthRow, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error)
	GetScreenshot(ctx context.Context, id string) (Screenshot, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetTranslation(ctx context.Context, arg GetTranslationParams) (Translation, error)
	GetTranslationBySubID(ctx context.Context, subID pgtype.Int8) (Translation, error)
	GetTranslationForUpdate(ctx context.Context, arg GetTranslationForUpdateParams) (Translation, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	InsertActivity(ctx context.Context, arg InsertActivityParams) error
	InsertTranslationHistory(ctx context.Context, arg InsertTranslationHistoryParams) error
	ListAPIKeysByProject(ctx context.Context, projectID pgtype.Text) ([]ApiKey, error)
	ListCommentsForTranslation(ctx context.Context, translationID pgtype.Text) ([]ListCommentsForTranslationRow, error)
	ListKeyHistory(ctx context.Context, arg ListKeyHistoryParams) ([]TranslationHistory, error)
	ListKeyScreenshotRegions(ctx context.Context, keyID string) ([]ListKeyScreenshotRegionsRow, error)
	ListKeys(ctx context.Context, arg ListKeysParams) ([]TranslationKey, error)
	ListLanguages(ctx context.Context, projectID string) ([]Language, error)
	ListNamespaces(ctx context.Context, projectID string) ([]Namespace, error)
	ListPATsByUser(ctx context.Context, ownerUserID pgtype.Text) ([]ApiKey, error)
	ListProjectActivity(ctx context.Context, arg ListProjectActivityParams) ([]Activity, error)
	ListProjectMemberLanguageIDs(ctx context.Context, memberID string) ([]string, error)
	ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error)
	ListProjectsForUser(ctx context.Context, userID string) ([]Project, error)
	ListTranslationHistory(ctx context.Context, arg ListTranslationHistoryParams) ([]ListTranslationHistoryRow, error)
	ListTranslationsForKey(ctx context.Context, keyID string) ([]Translation, error)
	ListTranslationsForKeys(ctx context.Context, dollar_1 []string) ([]Translation, error)
	ListUserOrganizations(ctx context.Context, userID string) ([]Organization, error)
	MarkSiblingsOutdated(ctx context.Context, arg MarkSiblingsOutdatedParams) ([]Translation, error)
	ResolveComment(ctx context.Context, arg ResolveCommentParams) (Comment, error)
	RevokeAPIKey(ctx context.Context, id string) error
	SetKeySourceHash(ctx context.Context, arg SetKeySourceHashParams) error
	SetProjectBaseLanguage(ctx context.Context, arg SetProjectBaseLanguageParams) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SoftDeleteKey(ctx context.Context, id string) error
	SoftDeleteProject(ctx context.Context, id string) error
	TouchAPIKey(ctx context.Context, id string) error
	UnresolveComment(ctx context.Context, id string) (Comment, error)
	UpdateKey(ctx context.Context, arg UpdateKeyParams) (TranslationKey, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) (Translation, error)
}

var _ Querier = (*Queries)(nil)
