// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProjectMemberLanguage(ctx context.Context, arg AddProjectMemberLanguageParams) error
	// Atomically grab the oldest queued task and mark it running. FOR UPDATE SKIP
	// LOCKED makes this safe even if more than one worker ever runs concurrently.
	ClaimNextTask(ctx context.Context) (Task, error)
	ClearProjectMemberLanguages(ctx context.Context, memberID string) error
	// Clear error too: a task may carry a stale error from a prior partial run that
	// was requeued by RecoverRunningTasks and then succeeded.
	CompleteTask(ctx context.Context, arg CompleteTaskParams) error
	CountKeys(ctx context.Context, projectID string) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateGlossaryTerm(ctx context.Context, arg CreateGlossaryTermParams) (GlossaryTerm, error)
	CreateKey(ctx context.Context, arg CreateKeyParams) (TranslationKey, error)
	CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error)
	CreateNamespace(ctx context.Context, arg CreateNamespaceParams) (Namespace, error)
	CreateOrgMembership(ctx context.Context, arg CreateOrgMembershipParams) (OrgMembership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error)
	CreateScreenshot(ctx context.Context, arg CreateScreenshotParams) (Screenshot, error)
	CreateScreenshotRegion(ctx context.Context, arg CreateScreenshotRegionParams) (ScreenshotRegion, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTranslation(ctx context.Context, arg CreateTranslationParams) (Translation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteGlossaryTerm(ctx context.Context, id string) error
	DeleteLanguage(ctx context.Context, id string) error
	DeleteMTConfig(ctx context.Context, projectID string) error
	DeleteProjectMember(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	DeleteWebhook(ctx context.Context, id string) error
	// Clear result for the symmetric reason (a requeued run that then fails).
	FailTask(ctx context.Context, arg FailTaskParams) error
	FindTMExact(ctx context.Context, arg FindTMExactParams) ([]FindTMExactRow, error)
	FindTMFuzzy(ctx context.Context, arg FindTMFuzzyParams) ([]FindTMFuzzyRow, error)
	// User-bound tokens (PATs, unlocked editor tokens) are rejected once their
	// owner is deactivated — so deactivation immediately revokes access, mirroring
	// session resolution. Unattended keys (no owner, e.g. read-only editor tokens)
	// are unaffected.
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error)
	GetComment(ctx context.Context, id string) (Comment, error)
	GetCommentProjectID(ctx context.Context, id string) (string, error)
	GetGlossaryTerm(ctx context.Context, id string) (GlossaryTerm, error)
	GetKey(ctx context.Context, id string) (TranslationKey, error)
	GetLanguage(ctx context.Context, id string) (Language, error)
	GetLanguageByTag(ctx context.Context, arg GetLanguageByTagParams) (Language, error)
	GetMTConfig(ctx context.Context, projectID string) (MtConfig, error)
	GetNamespaceByName(ctx context.Context, arg GetNamespaceByNameParams) (Namespace, error)
	GetOrgMembership(ctx context.Context, arg GetOrgMembershipParams) (OrgMembership, error)
	GetOrganization(ctx context.Context, id string) (Organization, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectForAuth(ctx context.Context, id string) (GetProjectForAuthRow, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error)
	GetProjectMemberByID(ctx context.Context, id string) (ProjectMember, error)
	GetScreenshot(ctx context.Context, id string) (Screenshot, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetTranslation(ctx context.Context, arg GetTranslationParams) (Translation, error)
	GetTranslationBySubID(ctx context.Context, subID pgtype.Int8) (Translation, error)
	GetTranslationForUpdate(ctx context.Context, arg GetTranslationForUpdateParams) (Translation, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetWebhook(ctx context.Context, id string) (Webhook, error)
	InsertActivity(ctx context.Context, arg InsertActivityParams) error
	InsertTMSegment(ctx context.Context, arg InsertTMSegmentParams) error
	// Like InsertTMSegment but RETURNs the id, so the TMX importer can tell a fresh
	// insert (row returned) from a deduped conflict (pgx.ErrNoRows).
	InsertTMSegmentReturning(ctx context.Context, arg InsertTMSegmentReturningParams) (string, error)
	InsertTranslationHistory(ctx context.Context, arg InsertTranslationHistoryParams) error
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) error
	ListAPIKeysByProject(ctx context.Context, projectID pgtype.Text) ([]ApiKey, error)
	ListActiveWebhooks(ctx context.Context, projectID string) ([]Webhook, error)
	// Recent project activity enriched for display. key_id/language_id are plain
	// text (no FK), so LEFT JOINs tolerate deleted keys/languages.
	ListActivityFeed(ctx context.Context, arg ListActivityFeedParams) ([]ListActivityFeedRow, error)
	ListCommentsForTranslation(ctx context.Context, translationID pgtype.Text) ([]ListCommentsForTranslationRow, error)
	ListGlossaryTerms(ctx context.Context, projectID string) ([]GlossaryTerm, error)
	ListGlossaryTranslationsByProject(ctx context.Context, projectID string) ([]GlossaryTranslation, error)
	ListKeyHistory(ctx context.Context, arg ListKeyHistoryParams) ([]TranslationHistory, error)
	ListKeyScreenshotRegions(ctx context.Context, keyID string) ([]ListKeyScreenshotRegionsRow, error)
	ListKeys(ctx context.Context, arg ListKeysParams) ([]TranslationKey, error)
	ListLanguages(ctx context.Context, projectID string) ([]Language, error)
	ListNamespaces(ctx context.Context, projectID string) ([]Namespace, error)
	ListPATsByUser(ctx context.Context, ownerUserID pgtype.Text) ([]ApiKey, error)
	ListProjectActivity(ctx context.Context, arg ListProjectActivityParams) ([]Activity, error)
	ListProjectMemberLanguageIDs(ctx context.Context, memberID string) ([]string, error)
	ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error)
	ListProjectsForUser(ctx context.Context, userID string) ([]Project, error)
	// Dump TM segments for export, optionally narrowed to a source/target lang pair
	// (pass '' to skip a filter).
	ListTMSegments(ctx context.Context, arg ListTMSegmentsParams) ([]ListTMSegmentsRow, error)
	ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error)
	ListTranslationHistory(ctx context.Context, arg ListTranslationHistoryParams) ([]ListTranslationHistoryRow, error)
	ListTranslationsForKey(ctx context.Context, keyID string) ([]Translation, error)
	ListTranslationsForKeys(ctx context.Context, dollar_1 []string) ([]Translation, error)
	ListUserOrganizations(ctx context.Context, userID string) ([]Organization, error)
	ListWebhookDeliveries(ctx context.Context, webhookID string) ([]WebhookDelivery, error)
	ListWebhooks(ctx context.Context, projectID string) ([]Webhook, error)
	MarkSiblingsOutdated(ctx context.Context, arg MarkSiblingsOutdatedParams) ([]Translation, error)
	MatchGlossary(ctx context.Context, arg MatchGlossaryParams) ([]MatchGlossaryRow, error)
	// On boot, any task still marked running is orphaned (the worker that owned it
	// died); requeue it so a single-instance deployment recovers cleanly. Reset the
	// progress counters so a polling client doesn't briefly see last-run's numbers.
	RecoverRunningTasks(ctx context.Context) error
	ResolveComment(ctx context.Context, arg ResolveCommentParams) (Comment, error)
	RevokeAPIKey(ctx context.Context, id string) error
	SetKeySourceHash(ctx context.Context, arg SetKeySourceHashParams) error
	SetProjectBaseLanguage(ctx context.Context, arg SetProjectBaseLanguageParams) error
	SetTaskProgress(ctx context.Context, arg SetTaskProgressParams) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SoftDeleteKey(ctx context.Context, id string) error
	SoftDeleteProject(ctx context.Context, id string) error
	TouchAPIKey(ctx context.Context, id string) error
	UnresolveComment(ctx context.Context, id string) (Comment, error)
	UpdateKey(ctx context.Context, arg UpdateKeyParams) (TranslationKey, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error
	UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) (Translation, error)
	UpsertGlossaryTranslation(ctx context.Context, arg UpsertGlossaryTranslationParams) (GlossaryTranslation, error)
	UpsertMTConfig(ctx context.Context, arg UpsertMTConfigParams) (MtConfig, error)
}

var _ Querier = (*Queries)(nil)
