// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: screenshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScreenshot = `-- name: CreateScreenshot :one
INSERT INTO screenshots (id, project_id, storage_key, name, width, height, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, storage_key, name, width, height, created_by, created_at
`

type CreateScreenshotParams struct {
	ID         string      `json:"id"`
	ProjectID  string      `json:"projectId"`
	StorageKey string      `json:"storageKey"`
	Name       string      `json:"name"`
	Width      int32       `json:"width"`
	Height     int32       `json:"height"`
	CreatedBy  pgtype.Text `json:"createdBy"`
}

func (q *Queries) CreateScreenshot(ctx context.Context, arg CreateScreenshotParams) (Screenshot, error) {
	row := q.db.QueryRow(ctx, createScreenshot,
		arg.ID,
		arg.ProjectID,
		arg.StorageKey,
		arg.Name,
		arg.Width,
		arg.Height,
		arg.CreatedBy,
	)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StorageKey,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createScreenshotRegion = `-- name: CreateScreenshotRegion :one
INSERT INTO screenshot_regions (id, screenshot_id, key_id, translation_id, x, y, w, h)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, screenshot_id, key_id, translation_id, x, y, w, h, created_at
`

type CreateScreenshotRegionParams struct {
	ID            string      `json:"id"`
	ScreenshotID  string      `json:"screenshotId"`
	KeyID         string      `json:"keyId"`
	TranslationID pgtype.Text `json:"translationId"`
	X             int32       `json:"x"`
	Y             int32       `json:"y"`
	W             int32       `json:"w"`
	H             int32       `json:"h"`
}

func (q *Queries) CreateScreenshotRegion(ctx context.Context, arg CreateScreenshotRegionParams) (ScreenshotRegion, error) {
	row := q.db.QueryRow(ctx, createScreenshotRegion,
		arg.ID,
		arg.ScreenshotID,
		arg.KeyID,
		arg.TranslationID,
		arg.X,
		arg.Y,
		arg.W,
		arg.H,
	)
	var i ScreenshotRegion
	err := row.Scan(
		&i.ID,
		&i.ScreenshotID,
		&i.KeyID,
		&i.TranslationID,
		&i.X,
		&i.Y,
		&i.W,
		&i.H,
		&i.CreatedAt,
	)
	return i, err
}

const getScreenshot = `-- name: GetScreenshot :one
SELECT id, project_id, storage_key, name, width, height, created_by, created_at FROM screenshots WHERE id = $1
`

func (q *Queries) GetScreenshot(ctx context.Context, id string) (Screenshot, error) {
	row := q.db.QueryRow(ctx, getScreenshot, id)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StorageKey,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listKeyScreenshotRegions = `-- name: ListKeyScreenshotRegions :many
SELECT s.id, s.project_id, s.storage_key, s.name, s.width, s.height, s.created_by, s.created_at, r.id, r.screenshot_id, r.key_id, r.translation_id, r.x, r.y, r.w, r.h, r.created_at
FROM screenshot_regions r
JOIN screenshots s ON s.id = r.screenshot_id
WHERE r.key_id = $1
ORDER BY s.created_at DESC, r.id
`

type ListKeyScreenshotRegionsRow struct {
	Screenshot       Screenshot       `json:"screenshot"`
	ScreenshotRegion ScreenshotRegion `json:"screenshotRegion"`
}

func (q *Queries) ListKeyScreenshotRegions(ctx context.Context, keyID string) ([]ListKeyScreenshotRegionsRow, error) {
	rows, err := q.db.Query(ctx, listKeyScreenshotRegions, keyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeyScreenshotRegionsRow{}
	for rows.Next() {
		var i ListKeyScreenshotRegionsRow
		if err := rows.Scan(
			&i.Screenshot.ID,
			&i.Screenshot.ProjectID,
			&i.Screenshot.StorageKey,
			&i.Screenshot.Name,
			&i.Screenshot.Width,
			&i.Screenshot.Height,
			&i.Screenshot.CreatedBy,
			&i.Screenshot.CreatedAt,
			&i.ScreenshotRegion.ID,
			&i.ScreenshotRegion.ScreenshotID,
			&i.ScreenshotRegion.KeyID,
			&i.ScreenshotRegion.TranslationID,
			&i.ScreenshotRegion.X,
			&i.ScreenshotRegion.Y,
			&i.ScreenshotRegion.W,
			&i.ScreenshotRegion.H,
			&i.ScreenshotRegion.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
