// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, expires_at, user_agent, ip, created_at
`

type CreateSessionParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"userId"`
	TokenHash string             `json:"tokenHash"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	UserAgent pgtype.Text        `json:"userAgent"`
	Ip        pgtype.Text        `json:"ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.expires_at, sessions.user_agent, sessions.ip, sessions.created_at, users.id, users.email, users.password_hash, users.name, users.avatar_url, users.is_active, users.created_at, users.updated_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > now()
  AND users.is_active = true
`

type GetSessionByTokenHashRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.ExpiresAt,
		&i.Session.UserAgent,
		&i.Session.Ip,
		&i.Session.CreatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.Name,
		&i.User.AvatarUrl,
		&i.User.IsActive,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}
