// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextTask = `-- name: ClaimNextTask :one
UPDATE tasks
SET status = 'running', started_at = now()
WHERE id = (
  SELECT id FROM tasks
  WHERE status = 'queued'
  ORDER BY created_at, id
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING id, project_id, type, status, progress, total, processed, result, error, created_by, created_at, started_at, finished_at, payload
`

// Atomically grab the oldest queued task and mark it running. FOR UPDATE SKIP
// LOCKED makes this safe even if more than one worker ever runs concurrently.
func (q *Queries) ClaimNextTask(ctx context.Context) (Task, error) {
	row := q.db.QueryRow(ctx, claimNextTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Total,
		&i.Processed,
		&i.Result,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Payload,
	)
	return i, err
}

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks
SET status = 'succeeded', result = $2, error = NULL, progress = 100, finished_at = now()
WHERE id = $1
`

type CompleteTaskParams struct {
	ID     string `json:"id"`
	Result []byte `json:"result"`
}

// Clear error too: a task may carry a stale error from a prior partial run that
// was requeued by RecoverRunningTasks and then succeeded.
func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.Exec(ctx, completeTask, arg.ID, arg.Result)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, project_id, type, payload, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, type, status, progress, total, processed, result, error, created_by, created_at, started_at, finished_at, payload
`

type CreateTaskParams struct {
	ID        string      `json:"id"`
	ProjectID pgtype.Text `json:"projectId"`
	Type      TaskType    `json:"type"`
	Payload   []byte      `json:"payload"`
	CreatedBy pgtype.Text `json:"createdBy"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Payload,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Total,
		&i.Processed,
		&i.Result,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Payload,
	)
	return i, err
}

const failTask = `-- name: FailTask :exec
UPDATE tasks
SET status = 'failed', error = $2, result = NULL, finished_at = now()
WHERE id = $1
`

type FailTaskParams struct {
	ID    string      `json:"id"`
	Error pgtype.Text `json:"error"`
}

// Clear result for the symmetric reason (a requeued run that then fails).
func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.Exec(ctx, failTask, arg.ID, arg.Error)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, type, status, progress, total, processed, result, error, created_by, created_at, started_at, finished_at, payload FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Total,
		&i.Processed,
		&i.Result,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Payload,
	)
	return i, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, type, status, progress, total, processed, result, error, created_by, created_at, started_at, finished_at, payload FROM tasks
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTasksByProjectParams struct {
	ProjectID pgtype.Text `json:"projectId"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Total,
			&i.Processed,
			&i.Result,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverRunningTasks = `-- name: RecoverRunningTasks :exec
UPDATE tasks
SET status = 'queued', started_at = NULL, progress = 0, processed = NULL, total = NULL
WHERE status = 'running'
`

// On boot, any task still marked running is orphaned (the worker that owned it
// died); requeue it so a single-instance deployment recovers cleanly. Reset the
// progress counters so a polling client doesn't briefly see last-run's numbers.
func (q *Queries) RecoverRunningTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverRunningTasks)
	return err
}

const setTaskProgress = `-- name: SetTaskProgress :exec
UPDATE tasks SET processed = $2, total = $3, progress = $4 WHERE id = $1
`

type SetTaskProgressParams struct {
	ID        string      `json:"id"`
	Processed pgtype.Int4 `json:"processed"`
	Total     pgtype.Int4 `json:"total"`
	Progress  int32       `json:"progress"`
}

func (q *Queries) SetTaskProgress(ctx context.Context, arg SetTaskProgressParams) error {
	_, err := q.db.Exec(ctx, setTaskProgress,
		arg.ID,
		arg.Processed,
		arg.Total,
		arg.Progress,
	)
	return err
}
