// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tm.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findTMExact = `-- name: FindTMExact :many
SELECT id, source_text, target_text
FROM tm_segments
WHERE project_id = $1
  AND source_lang = $2
  AND target_lang = $3
  AND source_hash = $4
LIMIT 5
`

type FindTMExactParams struct {
	ProjectID  string `json:"projectId"`
	SourceLang string `json:"sourceLang"`
	TargetLang string `json:"targetLang"`
	SourceHash string `json:"sourceHash"`
}

type FindTMExactRow struct {
	ID         string `json:"id"`
	SourceText string `json:"sourceText"`
	TargetText string `json:"targetText"`
}

func (q *Queries) FindTMExact(ctx context.Context, arg FindTMExactParams) ([]FindTMExactRow, error) {
	rows, err := q.db.Query(ctx, findTMExact,
		arg.ProjectID,
		arg.SourceLang,
		arg.TargetLang,
		arg.SourceHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTMExactRow{}
	for rows.Next() {
		var i FindTMExactRow
		if err := rows.Scan(&i.ID, &i.SourceText, &i.TargetText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTMFuzzy = `-- name: FindTMFuzzy :many
SELECT id, source_text, target_text,
       (similarity(lower(source_text), lower($1)))::float8 AS score
FROM tm_segments
WHERE project_id = $2
  AND source_lang = $3
  AND target_lang = $4
  AND source_text <> $1
  AND lower(source_text) % lower($1)
ORDER BY score DESC
LIMIT $5
`

type FindTMFuzzyParams struct {
	Query      string `json:"query"`
	ProjectID  string `json:"projectId"`
	SourceLang string `json:"sourceLang"`
	TargetLang string `json:"targetLang"`
	Lim        int32  `json:"lim"`
}

type FindTMFuzzyRow struct {
	ID         string  `json:"id"`
	SourceText string  `json:"sourceText"`
	TargetText string  `json:"targetText"`
	Score      float64 `json:"score"`
}

func (q *Queries) FindTMFuzzy(ctx context.Context, arg FindTMFuzzyParams) ([]FindTMFuzzyRow, error) {
	rows, err := q.db.Query(ctx, findTMFuzzy,
		arg.Query,
		arg.ProjectID,
		arg.SourceLang,
		arg.TargetLang,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTMFuzzyRow{}
	for rows.Next() {
		var i FindTMFuzzyRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceText,
			&i.TargetText,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTMSegment = `-- name: InsertTMSegment :exec
INSERT INTO tm_segments (id, project_id, source_lang, target_lang, source_text, target_text, source_hash, key_id, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (project_id, source_lang, target_lang, source_hash, target_text) DO NOTHING
`

type InsertTMSegmentParams struct {
	ID         string      `json:"id"`
	ProjectID  string      `json:"projectId"`
	SourceLang string      `json:"sourceLang"`
	TargetLang string      `json:"targetLang"`
	SourceText string      `json:"sourceText"`
	TargetText string      `json:"targetText"`
	SourceHash string      `json:"sourceHash"`
	KeyID      pgtype.Text `json:"keyId"`
	Origin     string      `json:"origin"`
}

func (q *Queries) InsertTMSegment(ctx context.Context, arg InsertTMSegmentParams) error {
	_, err := q.db.Exec(ctx, insertTMSegment,
		arg.ID,
		arg.ProjectID,
		arg.SourceLang,
		arg.TargetLang,
		arg.SourceText,
		arg.TargetText,
		arg.SourceHash,
		arg.KeyID,
		arg.Origin,
	)
	return err
}
