// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTranslation = `-- name: CreateTranslation :one
INSERT INTO translations (id, key_id, language_id, text, state, origin, is_machine, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, key_id, language_id, text, state, origin, is_machine, sub_id, version, updated_by, created_at, updated_at
`

type CreateTranslationParams struct {
	ID         string            `json:"id"`
	KeyID      string            `json:"keyId"`
	LanguageID string            `json:"languageId"`
	Text       pgtype.Text       `json:"text"`
	State      TranslationState  `json:"state"`
	Origin     TranslationOrigin `json:"origin"`
	IsMachine  bool              `json:"isMachine"`
	UpdatedBy  pgtype.Text       `json:"updatedBy"`
}

func (q *Queries) CreateTranslation(ctx context.Context, arg CreateTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, createTranslation,
		arg.ID,
		arg.KeyID,
		arg.LanguageID,
		arg.Text,
		arg.State,
		arg.Origin,
		arg.IsMachine,
		arg.UpdatedBy,
	)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.LanguageID,
		&i.Text,
		&i.State,
		&i.Origin,
		&i.IsMachine,
		&i.SubID,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranslation = `-- name: GetTranslation :one
SELECT id, key_id, language_id, text, state, origin, is_machine, sub_id, version, updated_by, created_at, updated_at FROM translations WHERE key_id = $1 AND language_id = $2
`

type GetTranslationParams struct {
	KeyID      string `json:"keyId"`
	LanguageID string `json:"languageId"`
}

func (q *Queries) GetTranslation(ctx context.Context, arg GetTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, getTranslation, arg.KeyID, arg.LanguageID)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.LanguageID,
		&i.Text,
		&i.State,
		&i.Origin,
		&i.IsMachine,
		&i.SubID,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranslationBySubID = `-- name: GetTranslationBySubID :one
SELECT id, key_id, language_id, text, state, origin, is_machine, sub_id, version, updated_by, created_at, updated_at FROM translations WHERE sub_id = $1
`

func (q *Queries) GetTranslationBySubID(ctx context.Context, subID pgtype.Int8) (Translation, error) {
	row := q.db.QueryRow(ctx, getTranslationBySubID, subID)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.LanguageID,
		&i.Text,
		&i.State,
		&i.Origin,
		&i.IsMachine,
		&i.SubID,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranslationForUpdate = `-- name: GetTranslationForUpdate :one
SELECT id, key_id, language_id, text, state, origin, is_machine, sub_id, version, updated_by, created_at, updated_at FROM translations WHERE key_id = $1 AND language_id = $2 FOR UPDATE
`

type GetTranslationForUpdateParams struct {
	KeyID      string `json:"keyId"`
	LanguageID string `json:"languageId"`
}

func (q *Queries) GetTranslationForUpdate(ctx context.Context, arg GetTranslationForUpdateParams) (Translation, error) {
	row := q.db.QueryRow(ctx, getTranslationForUpdate, arg.KeyID, arg.LanguageID)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.LanguageID,
		&i.Text,
		&i.State,
		&i.Origin,
		&i.IsMachine,
		&i.SubID,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity (id, project_id, type, actor_id, actor_kind, key_id, translation_id, language_id, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertActivityParams struct {
	ID            string       `json:"id"`
	ProjectID     string       `json:"projectId"`
	Type          ActivityType `json:"type"`
	ActorID       pgtype.Text  `json:"actorId"`
	ActorKind     AuthorKind   `json:"actorKind"`
	KeyID         pgtype.Text  `json:"keyId"`
	TranslationID pgtype.Text  `json:"translationId"`
	LanguageID    pgtype.Text  `json:"languageId"`
	Meta          []byte       `json:"meta"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.ActorID,
		arg.ActorKind,
		arg.KeyID,
		arg.TranslationID,
		arg.LanguageID,
		arg.Meta,
	)
	return err
}

const insertTranslationHistory = `-- name: InsertTranslationHistory :exec
INSERT INTO translation_history
  (id, translation_id, key_id, language_id, old_text, new_text, old_state, new_state, origin, author_kind, author_id, api_key_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertTranslationHistoryParams struct {
	ID            string               `json:"id"`
	TranslationID string               `json:"translationId"`
	KeyID         string               `json:"keyId"`
	LanguageID    string               `json:"languageId"`
	OldText       pgtype.Text          `json:"oldText"`
	NewText       pgtype.Text          `json:"newText"`
	OldState      NullTranslationState `json:"oldState"`
	NewState      NullTranslationState `json:"newState"`
	Origin        TranslationOrigin    `json:"origin"`
	AuthorKind    AuthorKind           `json:"authorKind"`
	AuthorID      pgtype.Text          `json:"authorId"`
	ApiKeyID      pgtype.Text          `json:"apiKeyId"`
}

func (q *Queries) InsertTranslationHistory(ctx context.Context, arg InsertTranslationHistoryParams) error {
	_, err := q.db.Exec(ctx, insertTranslationHistory,
		arg.ID,
		arg.TranslationID,
		arg.KeyID,
		arg.LanguageID,
		arg.OldText,
		arg.NewText,
		arg.OldState,
		arg.NewState,
		arg.Origin,
		arg.AuthorKind,
		arg.AuthorID,
		arg.ApiKeyID,
	)
	return err
}

const listKeyHistory = `-- name: ListKeyHistory :many
SELECT id, translation_id, key_id, language_id, old_text, new_text, old_state, new_state, origin, author_kind, author_id, api_key_id, created_at FROM translation_history WHERE key_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListKeyHistoryParams struct {
	KeyID string `json:"keyId"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListKeyHistory(ctx context.Context, arg ListKeyHistoryParams) ([]TranslationHistory, error) {
	rows, err := q.db.Query(ctx, listKeyHistory, arg.KeyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranslationHistory{}
	for rows.Next() {
		var i TranslationHistory
		if err := rows.Scan(
			&i.ID,
			&i.TranslationID,
			&i.KeyID,
			&i.LanguageID,
			&i.OldText,
			&i.NewText,
			&i.OldState,
			&i.NewState,
			&i.Origin,
			&i.AuthorKind,
			&i.AuthorID,
			&i.ApiKeyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectActivity = `-- name: ListProjectActivity :many
SELECT id, project_id, type, actor_id, actor_kind, key_id, translation_id, language_id, meta, created_at FROM activity WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListProjectActivityParams struct {
	ProjectID string `json:"projectId"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListProjectActivity(ctx context.Context, arg ListProjectActivityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listProjectActivity, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.ActorID,
			&i.ActorKind,
			&i.KeyID,
			&i.TranslationID,
			&i.LanguageID,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsForKey = `-- name: ListTranslationsForKey :many
SELECT id, key_id, language_id, text, state, origin, is_machine, sub_id, version, updated_by, created_at, updated_at FROM translations WHERE key_id = $1
`

func (q *Queries) ListTranslationsForKey(ctx context.Context, keyID string) ([]Translation, error) {
	rows, err := q.db.Query(ctx, listTranslationsForKey, keyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Translation{}
	for rows.Next() {
		var i Translation
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.LanguageID,
			&i.Text,
			&i.State,
			&i.Origin,
			&i.IsMachine,
			&i.SubID,
			&i.Version,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSiblingsOutdated = `-- name: MarkSiblingsOutdated :many
UPDATE translations
SET state = 'outdated', version = version + 1, updated_at = now()
WHERE key_id = $1 AND language_id <> $2 AND state IN ('translated', 'reviewed')
RETURNING id, key_id, language_id, text, state, origin, is_machine, sub_id, version, updated_by, created_at, updated_at
`

type MarkSiblingsOutdatedParams struct {
	KeyID      string `json:"keyId"`
	LanguageID string `json:"languageId"`
}

func (q *Queries) MarkSiblingsOutdated(ctx context.Context, arg MarkSiblingsOutdatedParams) ([]Translation, error) {
	rows, err := q.db.Query(ctx, markSiblingsOutdated, arg.KeyID, arg.LanguageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Translation{}
	for rows.Next() {
		var i Translation
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.LanguageID,
			&i.Text,
			&i.State,
			&i.Origin,
			&i.IsMachine,
			&i.SubID,
			&i.Version,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranslation = `-- name: UpdateTranslation :one
UPDATE translations
SET text = $2, state = $3, origin = $4, is_machine = $5,
    version = version + 1, updated_by = $6, updated_at = now()
WHERE id = $1
RETURNING id, key_id, language_id, text, state, origin, is_machine, sub_id, version, updated_by, created_at, updated_at
`

type UpdateTranslationParams struct {
	ID        string            `json:"id"`
	Text      pgtype.Text       `json:"text"`
	State     TranslationState  `json:"state"`
	Origin    TranslationOrigin `json:"origin"`
	IsMachine bool              `json:"isMachine"`
	UpdatedBy pgtype.Text       `json:"updatedBy"`
}

func (q *Queries) UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, updateTranslation,
		arg.ID,
		arg.Text,
		arg.State,
		arg.Origin,
		arg.IsMachine,
		arg.UpdatedBy,
	)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.LanguageID,
		&i.Text,
		&i.State,
		&i.Origin,
		&i.IsMachine,
		&i.SubID,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
