// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, project_id, url, secret, events, active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, url, secret, events, active, created_at
`

type CreateWebhookParams struct {
	ID        string   `json:"id"`
	ProjectID string   `json:"projectId"`
	Url       string   `json:"url"`
	Secret    []byte   `json:"secret"`
	Events    []string `json:"events"`
	Active    bool     `json:"active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ID,
		arg.ProjectID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Active,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :exec
INSERT INTO webhook_deliveries (id, webhook_id, event, status_code, success, error)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertWebhookDeliveryParams struct {
	ID         string `json:"id"`
	WebhookID  string `json:"webhookId"`
	Event      string `json:"event"`
	StatusCode int32  `json:"statusCode"`
	Success    bool   `json:"success"`
	Error      string `json:"error"`
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.ID,
		arg.WebhookID,
		arg.Event,
		arg.StatusCode,
		arg.Success,
		arg.Error,
	)
	return err
}

const listActiveWebhooks = `-- name: ListActiveWebhooks :many
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks WHERE project_id = $1 AND active = true
`

func (q *Queries) ListActiveWebhooks(ctx context.Context, projectID string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event, status_code, success, error, created_at FROM webhook_deliveries WHERE webhook_id = $1 ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListWebhookDeliveries(ctx context.Context, webhookID string) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, webhookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.StatusCode,
			&i.Success,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context, projectID string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
